version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '${POSTGRES_PORT}:5443'
    volumes:
      - ./db:/var/lib/postgresql/data